### ISSUE TITLE
Do not limit the interval times

### ISSUE THREAD

**Issue by c33s** [SecUSo/privacy-friendly-interval-timer#14]
some workouts are longer than 5 minutes, also the interval timer can used for other things than a workout, so the maximum time should not be limited at all.
al least allow 99minutes an 99 secs

**Comment by udopt** [comment]
I support this. Also, more granular control over interval times would be great. Sometimes, you do a high intensity workout and would like to set 15 seconds, but only 10 or 20 are allowed.

**Comment by sleep-yearning** [comment]
should be fixed with 82d0660
