### ISSUE TITLE
Adding exercises to intervals

### ISSUE THREAD

**Issue by bigzed** [SecUSo/privacy-friendly-interval-timer#20]
I would welcome it if one would be able to add the list of exercises to a block.
For example the following exercises:
* Push ups
* Pull ups
* Sit ups

would translate in to a block of 3 intervals each e.g. 1minute with 30sec rest. The app would not only display the current timer, but also the exercise one is supposed to do.

**Comment by Kamuno** [comment]
There is a special app for this functionality: 
See: https://github.com/SecUSo/privacy-friendly-circuit-training-exercises/
