### ISSUE TITLE
Do not limit the number of sets

### ISSUE THREAD

**Issue by udopt** [SecUSo/privacy-friendly-interval-timer#21]
Currently, there is a limit of 16 sets. Some workouts are longer, so it would be great to remove the limit or at least set it so something like 999 etc.

**Comment by toxynoid** [comment]
Absolutely. I was trying to use this interval timer in a test situation. 60 Questions (Sets) in 90 Minutes.

**Comment by mbnoimi** [comment]
Unfortunately it seems this project is dead so I manipulate this issue easily by editing XML files using  [Preferences Manager](https://f-droid.org/en/packages/fr.simon.marquis.preferencesmanager/) (usually I set `sets` to `30` instead of `16`)

**Comment by sleep-yearning** [comment]
should be fixed with 82d0660
