### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by udopt** [SecUSo/privacy-friendly-interval-timer#22]
I was wondering if there is still active development?

Some issues could easily be resolved by changing some constants in https://github.com/SecUSo/privacy-friendly-interval-timer/blob/master/app/src/main/java/org/secuso/privacyfriendlyintervaltimer/activities/MainActivity.java, such as

- https://github.com/SecUSo/privacy-friendly-interval-timer/issues/21
- https://github.com/SecUSo/privacy-friendly-interval-timer/issues/14
- https://github.com/SecUSo/privacy-friendly-interval-timer/issues/10

Would you be interested in a pull request?

**Comment by Kamuno** [comment]
Sorry for the silence, but we have very limited resources. If you find easy to fix issues in the future, we are very happy to accept pull requests,
These particular issues are fixed now.
